### ISSUE TITLE
Multilanguage Support

### ISSUE THREAD

**Issue by BijuuKrunos** [AlonsoAliaga/BetterBees#13]
Hello i would like to ask if its possible to add Multilanguage Support to this awesome Plugin, would be realy great :)

**Comment by AlonsoAliaga** [comment]
Glad you like it!
What does multilanguage support means exactly for this simple plugin?
This is just to display certain info about nests and bees

**Comment by BijuuKrunos** [comment]
I know there are not much messages but even for them it would be great for example todo something like:

Messages:
    Hive-Info:
        Default: "&bHoney&8: &a&l{HONEYLEVEL}&8/&7{MAXHONEYLEVEL} &8| &bBee&8: &a&l{BEES}"
        de_DE: "&bHonig&8: &a&l{HONEYLEVEL}&8/&7{MAXHONEYLEVEL} &8| &bBienen&8: &a&l{BEES}"

and that for all messages. or for the complete section like:
Messages-Default:
....

Messages-de_DE:
...

**Comment by AlonsoAliaga** [comment]
Issue is that i cannot track player language, i recommend you to use a plugin like Triton that allows you to use "placeholders" that will be converted to player language based on the language they select on that plugin. Imo that would be way better for other plugins too

**Comment by BijuuKrunos** [comment]
yeah i will use Triton for everything where it does not work internaly, but if possible i want to use it from the plugin itself. Cant you just check the Client Language from the player? others are doing it that way.

**Comment by AlonsoAliaga** [comment]
The thing is that doing such complex system for just 2 or 3 messages is nor worth it, thats why i suggest Triton as it allow managing almost all plugins easily without needing to add support for that in all plugins. Imagine creating a whole system (+ plugin recode) just for some messages

**Comment by BijuuKrunos** [comment]
cant imagine that xD. Ok thanks than i will do it here with Triton :)
