### ISSUE TITLE
Feature request: reload 

### ISSUE THREAD

**Issue by SlimeDog** [AlonsoAliaga/BetterBees#2]
Spigot 1.15.1
BetterBees 0.1-BETA

Please implement
>betterbees reload

from console or in-game, to reload the contents of config.yml

**Comment by AlonsoAliaga** [comment]
A command to reload messages could be added, however, reload all options to change booleans for hooks or similars would, i don't think would be needed, i personally think that a server restart should be required when changing options related to checks/events/hooks.

Working on messages reload 😃

**Comment by SlimeDog** [comment]
Many plugins manage to do so, but it's your plugin -- you make the decisions. The operative word in the title is "request".

**Comment by AlonsoAliaga** [comment]
Added reload command, it reloads certain things like messages.
