### ISSUE TITLE
Conflict between FluffyMachines and BetterBees

### ISSUE THREAD

**Issue by Zireaphus** [AlonsoAliaga/BetterBees#8]
**Describe the bug**
Small Fluffy Barrel (item do Slimefun) conflicts with the BetterBees plugin. When you break a Slimefun item with an artificial hive texture, you duplicate that item, generate the Slimefun item and an artificial hive.

**To Reproduce**
1. Add the Slimefun plugin and the FluffyMachine addon;
2. Place a Small Fluffy Barrels;
3. Break the item.

**Expected behavior**
When breaking a Slimefun item with the hive texture, you should not duplicate the item.

**Screenshots**
https://youtu.be/h5Qi441l_cU

**Important (please complete the following information):**
 - Java version: 8
 - Plugin version: v0.4-BETA
 - Server version: 1.16.3

**Additional context**
Slimefun's devs are already aware.

**Comment by AlonsoAliaga** [comment]
Hello, thanks for reporting the issue, could you join our discord server so i can send you dev builds to check if issue is fixed?
Discord link is: https://discord.gg/DEDaQhs

**Comment by AlonsoAliaga** [comment]
Fixed in 0.5-BETA (Pending to release for public access)
