### ISSUE TITLE
Problem with world

### ISSUE THREAD

**Issue by DjeyMute** [AlonsoAliaga/BetterBees#9]
Hi, 

I have a problem with your plugin it's workd only normally in my world "spawn".
In other worlds it only works if I take the item in hand and click right in the air....

**Important (please complete the following information):**
 - Java version: 16
 - Plugin version: 0.8
 - Server version :1.17.1
- NBTAPI : 2.8.0

**Comment by AlonsoAliaga** [comment]
✅ Solved in Discord server.
